// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RapidBootcamp.ETLSampel.RapidDw;

public partial class DimProduct
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string CategoryName { get; set; }

    public int Stock { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
}