// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RapidBootcamp.ETLSampel.RapidDw;

public partial class DimWallet
{
    public int WalletId { get; set; }

    public int? WalletOriginalKey { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerCity { get; set; }

    public string CustomerPhoneNumber { get; set; }

    public string WalletTypeName { get; set; }

    public decimal Saldo { get; set; }

    public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
}