// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RapidBootcamp.ETLSampel.RapidDw;

public partial class FactSale
{
    public int SalesId { get; set; }

    public int? ProductId { get; set; }

    public int? WalletId { get; set; }

    public string OrderHeaderId { get; set; }

    public int? OrderDetailOriginalId { get; set; }

    public int Qty { get; set; }

    public decimal Price { get; set; }

    public decimal TotalSales { get; set; }

    public virtual DimProduct Product { get; set; }

    public virtual DimWallet Wallet { get; set; }
}