// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RapidBootcamp.ETLSampel.RapidDb;

public partial class Shipping
{
    public int ShippingId { get; set; }

    public string ShippingMetode { get; set; }
}